# Name : Vasu Kalariya
# Roll : PE29

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
from sklearn.datasets import load_iris

data = load_iris()
ds = pd.DataFrame(data.data, columns=data.feature_names)
ds.shape

(150, 4)

In [23]:
X = ds.iloc[:,0:4].values
y = data.target
y = y.reshape(-1,1)

In [24]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Naïve Bayes Classifier

In [25]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()
classifier.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [26]:
y_pred = classifier.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
print()
print("Accuracy score : ",accuracy_score(y_test, y_pred))

[[13  0  0]
 [ 0 15  0]
 [ 0  1 16]]

Accuracy score :  0.9777777777777777


# Multinomial NB

In [ ]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()
clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
pred_y = clf.predict(X_test)

In [ ]:
c_m = confusion_matrix(y_test, pred_y)
print(c_m)
print()
print("Accuracy score : ",accuracy_score(y_test, pred_y))

[[13  0  0]
 [ 0 15  1]
 [ 0  1 15]]

Accuracy score :  0.9555555555555556
